/**
 * Extract user selections from chat messages.
 * These patterns match the messages generated by UI component callbacks.
 */

import { parse } from "date-fns";

// Pattern: "I'd like to book {serviceName}"
const SERVICE_PATTERN = /I'd like to book ([^.]+?)(?:\s+on\s+|$)/i;

// Pattern: "I'd like to book {serviceName} on {date}"
const DATE_PATTERN = /I'd like to book (.+?) on ([A-Z][a-z]+ \d{1,2}, \d{4})/i;

// Pattern: "I'd like the {time} slot for {serviceName} on {date}"
const TIME_PATTERN = /I'd like the (\d{1,2}:\d{2}(?:\s*[APap][Mm])?)\s+slot for (.+?) on ([A-Z][a-z]+ \d{1,2}, \d{4})/i;

/**
 * Extract service name from a user message selecting a service.
 */
export function extractServiceSelection(content: string): string | null {
  const match = content.match(SERVICE_PATTERN);
  if (match) {
    return match[1].trim();
  }
  return null;
}

/**
 * Extract service name and date from a user message selecting a date.
 */
export function extractDateSelection(
  content: string
): { serviceName: string; date: Date } | null {
  const match = content.match(DATE_PATTERN);
  if (match) {
    const serviceName = match[1].trim();
    const dateStr = match[2];
    // Parse date like "January 20, 2026"
    const date = parse(dateStr, "MMMM d, yyyy", new Date());
    if (!isNaN(date.getTime())) {
      return { serviceName, date };
    }
  }
  return null;
}

/**
 * Extract time, service name and date from a user message selecting a time slot.
 */
export function extractTimeSelection(
  content: string
): { time: string; serviceName: string; date: Date } | null {
  const match = content.match(TIME_PATTERN);
  if (match) {
    const time = match[1].trim();
    const serviceName = match[2].trim();
    const dateStr = match[3];
    const date = parse(dateStr, "MMMM d, yyyy", new Date());
    if (!isNaN(date.getTime())) {
      return { time, serviceName, date };
    }
  }
  return null;
}

/**
 * Extract selection information based on the type of UI component shown.
 * Returns the appropriate pre-selection value based on what the user selected.
 */
export interface SelectionContext {
  preSelectedServiceName?: string;
  preSelectedDate?: Date;
  preSelectedTime?: string;
}

export function extractSelectionFromNextMessage(
  nextMessageContent: string | undefined
): SelectionContext {
  if (!nextMessageContent) {
    return {};
  }

  const context: SelectionContext = {};

  // Try to extract time selection (most specific)
  const timeSelection = extractTimeSelection(nextMessageContent);
  if (timeSelection) {
    context.preSelectedTime = timeSelection.time;
    context.preSelectedDate = timeSelection.date;
    context.preSelectedServiceName = timeSelection.serviceName;
    return context;
  }

  // Try to extract date selection
  const dateSelection = extractDateSelection(nextMessageContent);
  if (dateSelection) {
    context.preSelectedDate = dateSelection.date;
    context.preSelectedServiceName = dateSelection.serviceName;
    return context;
  }

  // Try to extract service selection
  const serviceName = extractServiceSelection(nextMessageContent);
  if (serviceName) {
    context.preSelectedServiceName = serviceName;
    return context;
  }

  return context;
}
